name: build wheel
on:
  push:
    branches:
      - main

jobs:
  build-installer:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: pyproject.toml
          python-version: '3.12'
      - name: install pypa/build
        run: pip install --upgrade build
      - id: measurement-4
        name: Record Measurement After install pypa/build
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: install pypa/build
          task: get-measurement
      - name: setup frontend
        uses: ./.github/actions/install-frontend-deps
      - id: build_wheel
        name: build wheel
        run: ./scripts/build_wheel.sh
      - id: measurement-7
        name: Record Measurement After build wheel
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: build wheel
          task: get-measurement
      - name: upload python distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ${{ steps.build_wheel.outputs.DIST_PATH }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    timeout-minutes: 5
