name: frontend tests
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: invokeai/frontend/web
jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - id: changed-files
        if: ${{ inputs.always_run != true }}
        name: check for changed frontend files
        uses: tj-actions/changed-files@a284dc1814e3fd07f2e34267fc8f81227ed29fb8
        with:
          files_yaml: "frontend:\n  - 'invokeai/frontend/web/**'\n"
      - if: ${{ steps.changed-files.outputs.frontend_any_changed == 'true' || inputs.always_run
          == true }}
        name: install dependencies
        uses: ./.github/actions/install-frontend-deps
      - if: ${{ steps.changed-files.outputs.frontend_any_changed == 'true' || inputs.always_run
          == true }}
        name: vitest
        run: pnpm test:no-watch
        shell: bash
      - id: measurement-5
        name: Record Measurement After vitest
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: vitest
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    timeout-minutes: 10
