name: python tests

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      always_run:
        description: 'Force run all jobs'
        required: false
        default: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  matrix:
    env:
      PIP_USE_PEP517: '1'
    name: 'py${{ matrix.python-version }}: ${{ matrix.platform }}'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement

      - name: checkout
        uses: nschloe/action-cached-lfs-checkout@f46300cd8952454b9f0a21a3d133d4bd5684cfc2

      - id: changed-files
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.always_run != 'true' }}
        name: check for changed python files
        uses: tj-actions/changed-files@a284dc1814e3fd07f2e34267fc8f81227ed29fb8
        with:
          files_yaml: |
            python:
              - 'pyproject.toml'
              - 'invokeai/**'
              - '!invokeai/frontend/web/**'
              - 'tests/**'

      - if: ${{ steps.changed-files.outputs.python_any_changed == 'true' || (github.event_name == 'workflow_dispatch' && inputs.always_run == 'true') }}
        name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - if: ${{ steps.changed-files.outputs.python_any_changed == 'true' || (github.event_name == 'workflow_dispatch' && inputs.always_run == 'true') }}
        name: install dependencies
        run: pip install --upgrade pip && pip install -e ".[test]"

      - id: measurement-6
        name: Record Measurement After install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: install dependencies
          task: get-measurement

      - if: ${{ steps.changed-files.outputs.python_any_changed == 'true' || (github.event_name == 'workflow_dispatch' && inputs.always_run == 'true') }}
        name: run pytest
        run: pytest

      - id: measurement-8
        name: Record Measurement After run pytest
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: run pytest
          task: get-measurement

      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json

    strategy:
      matrix:
        include:
          - extra-index-url: https://download.pytorch.org/whl/cpu
            github-env: $GITHUB_ENV
            os: ubuntu-latest
            platform: linux-cpu
        platform:
          - linux-cpu
        python-version:
          - '3.11'
          - '3.12'
    timeout-minutes: 15
